version: '2'
services:

  front-envoy:
    build:
      context: .
      dockerfile: envoy.dockerfile
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  authz:
    build:
      context: .
      dockerfile: auth.dockerfile
    networks:
      envoymesh:
        aliases:
          - authz
    expose:
      - "8080"

  service1:
    build:
      context: .
      dockerfile: service.dockerfile
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "8080"
    ports:
      - "8080:8080"


networks:
  envoymesh: {}